### ISSUE TITLE
Move to an easily available heading font

### ISSUE THREAD

**Issue by saadulkh** [lvignoli/diapo#5]
It's a suggestion to update the default headings font to a beautiful `Quicksand` font.

Problems with `Avenir` font include:
- No online easy availability of full font family
- Not a part of Google fonts

Benefits of moving to `Quicksand` include:
- Easily available online at Google [fonts](https://fonts.google.com/specimen/Quicksand)
- It's an open-source font available at [github](https://github.com/andrew-paglinawan/QuicksandFamily)

Also, it might be a personal preference and in-case you do not agree, feel free to close this issue.

**Comment by lvignoli** [comment]
Avenir is shipped by default on macOS only, so we must provide an alternative.
I'll add a list of fallback fonts. I am not so sure about Quicksand: I'd rather add system fonts.
Of course the end-user can always customize it.

**Comment by lvignoli** [comment]
With fc124d9ace72951d17bfae48123f17c0ac4eab6d I have added `Inter` ([common web font with great traction](https://fonts.google.com/analytics)) as a first fallback then `Arial`.
For less common font I think we should let the user customize it.
